[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/local/bin/mold"]

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

# [target.x86_64-pc-windows-msvc]
# linker = "lld"
# rustflags = [
#   "-Lnative=/home/shane/.xwin/crt/lib/x86_64",
#   "-Lnative=/home/shane/.xwin/sdk/lib/um/x86_64",
#   "-Lnative=/home/shane/.xwin/sdk/lib/ucrt/x86_64"
# ]
